os:
  - linux
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "4"

before_script:
  # Fixes an annoying bug in ESLint on Node 4
  # https://github.com/babel/babel-eslint/issues/558
  # TODO: Remove when Node 4 is not supported anymore
  - npm install estraverse

script:
  - npm test

after_success:
  - npm install coveralls
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
